services:
  client:
    tty: true
    build:
      context: ./client
    environment:
      PORT: 3000
      PROXY_API: http://server:8080/
    ports:
      - 3000:3000
  server:
    tty: true
    build:
      context: ./server
    ports:
      - 8080:8080